title: Team Portal
description: Quick links & announcements
url: ""    # e.g., https://example.com
baseurl: "" # e.g., /team-portal
permalink: pretty
markdown: kramdown
theme: null
plugins:
  - jekyll-seo-tag   # Adds meta/OG tags (GitHub Pages–supported)
  - jekyll-feed      # Optional RSS feed