title: Team Portal
description: Quick links & announcements
url: ""    # e.g., https://example.com
baseurl: "" # e.g., /team-portal
permalink: pretty
markdown: kramdown
theme: null
plugins:
  - jekyll-feed  # Optional, can remove if not needed